### ISSUE TITLE
Customization?

### ISSUE THREAD

**Issue by kennetpostigo** [trevordmiller/nova#25]
Is there anyway to customize the syntax theme/ui theme from atom? Something that atom-material would allow you to do?
![screen shot 2016-09-22 at 1 40 16 pm](https://cloud.githubusercontent.com/assets/8888991/18759347/1b520258-80ca-11e6-8ce3-3624d9b1956d.png)

Id like to make the blue-grayish background color darker as it currently kinda hurts my eyes.

**Comment by trevordmiller** [comment]
Hi Kennet. Atom lets you customize anything you'd like for any theme or plugin with your stylesheets using css (less):
http://flight-manual.atom.io/using-atom/sections/basic-customization/

Although if you are looking for a color scheme with more contrast I suggest using another as Nova is not designed for accessibility.

Your screenshot does show that the icon packages don't match the Nova colors though, I will add support for the most popular Atom icon package so that it uses Nova colors.

Thanks for trying out Nova!
