### ISSUE TITLE
Selection color on website

### ISSUE THREAD

**Issue by aharris88** [trevordmiller/nova#41]
It might be nice to change the highlight/selection color on the website to cyan.

The style needed would be something like:

```css
::selection: {
  background: colors.normal.cyan
}
```

I would be happy to make a pull request, but since it's a pseudo selector, it would be in a stylesheet instead of an inline style on an element. I'm not sure if that would go in https://github.com/trevordmiller/nova/blob/master/src/components/Main.js or in https://github.com/trevordmiller/nova/blob/master/src/components/Home/Home.js.

I realize that you can change your highlight color globally on macOS at `System Preferences -> General -> Highlight color`, but it would be nice to just have this on the website.

**Comment by trevordmiller** [comment]
@aharris88 
Thanks for the feedback! I agree. This could go [in the `index.html` `<style>` with the other style reset selectors](https://github.com/trevordmiller/nova/blob/master/index.html#L10-L21); the cyan color would need to be hard-coded as I did with the input focus outline; I'd prefer to have the colors referenced programatically by `colors.normal.cyan` but am using default React inline styles everywhere else (which don't support psudo-selectors) and don't feel adding an extra library for this is worth it right now; so, I'd recommend to add it to the `index.html` inline reset and if this gets too big we can add a library like Aphrodite and place these in the `App.js` React styles. Feel free to submit a pull request [using the "CONTRIBUTING" guidelines](https://trevordmiller.github.io/nova); otherwise, I'll get to this :)
